"""
backend/tests/test_audio_pipeline.py
=====================================
Test suite for the Audio Input and Preprocessing Layer.

Covers:
  ─ backend/audio/decoder.py
      load_audio()
      check_ffmpeg()
      _decode_via_ffmpeg()
      _decode_wav_stdlib()
      normalize_audio() (removed from decoder — tested via preprocessing)

  ─ backend/audio/preprocessing.py
      preprocess_audio()
      normalize_waveform()
      validate_waveform()
      get_audio_info()

Sample files used (generated by test infrastructure when absent):
  samples/genuine/sine_440hz_44k_mono.wav    – 44.1 kHz mono  (tests resampling)
  samples/genuine/sine_220hz_16k_mono.wav    – 16 kHz mono    (already at target)
  samples/genuine/sine_300hz_8k_mono.wav     – 8 kHz mono     (tests upsampling)
  samples/genuine/sine_440hz_16k_quiet.wav   – 16 kHz, amplitude=0.01 (tests norm)
  samples/genuine/sine_440hz_22k_stereo.wav  – 22 kHz stereo  (tests ch mixing)
  samples/genuine/corrupt_file.wav           – garbage bytes   (tests error path)
  samples/genuine/empty_file.wav             – 0-byte file     (tests error path)

Run:
  python -m pytest backend/tests/test_audio_pipeline.py -v
or directly:
  python backend/tests/test_audio_pipeline.py
"""

from __future__ import annotations

import math
import os
import struct
import sys
import tempfile
import wave
from pathlib import Path

import numpy as np
import pytest

# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[2]   # VoiceCloneDetection-SIH/
SAMPLES_DIR  = PROJECT_ROOT / "samples" / "genuine"


def sample(name: str) -> Path:
    """Return the absolute path to a sample file."""
    return SAMPLES_DIR / name


# ---------------------------------------------------------------------------
# Test utilities
# ---------------------------------------------------------------------------

def _make_wav_bytes(
    sr: int = 16000,
    freq: float = 440.0,
    duration: float = 0.5,
    amplitude: float = 0.5,
    channels: int = 1,
    sampwidth: int = 2,
) -> bytes:
    """Create in-memory WAV bytes for a pure sine wave."""
    n = int(sr * duration)
    t = np.linspace(0, duration, n, endpoint=False)
    data = (amplitude * np.sin(2 * math.pi * freq * t)).astype(np.float32)
    if channels == 2:
        data = np.stack([data, data * 0.8], axis=1).flatten()
    pcm = (data * (2 ** (sampwidth * 8 - 1) - 1)).astype(
        np.int16 if sampwidth == 2 else np.int32
    )
    import io
    buf = io.BytesIO()
    with wave.open(buf, "wb") as wf:
        wf.setnchannels(channels)
        wf.setsampwidth(sampwidth)
        wf.setframerate(sr)
        wf.writeframes(pcm.tobytes())
    return buf.getvalue()


# ===========================================================================
# 1. DECODER TESTS  (backend/audio/decoder.py)
# ===========================================================================

class TestFFmpegAvailability:
    def test_check_ffmpeg_returns_bool(self):
        from backend.audio.decoder import check_ffmpeg
        result = check_ffmpeg()
        assert isinstance(result, bool)

    def test_ffmpeg_is_available(self):
        """FFmpeg must be installed for this project to function."""
        from backend.audio.decoder import check_ffmpeg
        assert check_ffmpeg(), (
            "FFmpeg is not found on PATH. "
            "Install it with: brew install ffmpeg"
        )


class TestLoadAudioReturnContract:
    """load_audio() must always return (1-D float32, int)."""

    def test_returns_tuple_of_two(self):
        from backend.audio.decoder import load_audio
        result = load_audio(sample("sine_440hz_16k_mono.wav"))
        assert isinstance(result, tuple) and len(result) == 2

    def test_waveform_is_ndarray(self):
        from backend.audio.decoder import load_audio
        waveform, _ = load_audio(sample("sine_440hz_16k_mono.wav"))
        assert isinstance(waveform, np.ndarray)

    def test_waveform_dtype_is_float32(self):
        from backend.audio.decoder import load_audio
        waveform, _ = load_audio(sample("sine_440hz_16k_mono.wav"))
        assert waveform.dtype == np.float32, (
            f"Expected float32, got {waveform.dtype}"
        )

    def test_waveform_is_1d(self):
        from backend.audio.decoder import load_audio
        waveform, _ = load_audio(sample("sine_440hz_16k_mono.wav"))
        assert waveform.ndim == 1, (
            f"Expected 1-D waveform, got shape {waveform.shape}"
        )

    def test_sample_rate_equals_target(self):
        from backend.audio.decoder import load_audio
        _, sr = load_audio(sample("sine_440hz_16k_mono.wav"), target_sr=16000)
        assert sr == 16000

    def test_sample_rate_custom_target(self):
        from backend.audio.decoder import load_audio
        _, sr = load_audio(sample("sine_440hz_16k_mono.wav"), target_sr=8000)
        assert sr == 8000

    def test_waveform_not_empty(self):
        from backend.audio.decoder import load_audio
        waveform, _ = load_audio(sample("sine_440hz_16k_mono.wav"))
        assert waveform.size > 0


class TestLoadAudioSampleCounts:
    """Verify that the number of output samples makes sense for the duration."""

    def test_1s_at_44k_resampled_to_16k(self):
        """1 s @ 44.1 kHz → ~16 000 samples when resampled to 16 kHz."""
        from backend.audio.decoder import load_audio
        waveform, sr = load_audio(
            sample("sine_440hz_44k_mono.wav"), target_sr=16000
        )
        assert sr == 16000
        # Allow ±5 % tolerance for resampler rounding
        assert abs(waveform.size - 16000) < 800, (
            f"Expected ~16000 samples for 1 s at 16 kHz, got {waveform.size}"
        )

    def test_05s_at_16k_stays_16k(self):
        """0.5 s @ 16 kHz → ~8 000 samples (no resampling)."""
        from backend.audio.decoder import load_audio
        waveform, sr = load_audio(
            sample("sine_220hz_16k_mono.wav"), target_sr=16000
        )
        assert sr == 16000
        assert abs(waveform.size - 8000) < 400

    def test_8k_upsampled_to_16k(self):
        """0.5 s @ 8 kHz → ~8 000 samples when upsampled to 16 kHz."""
        from backend.audio.decoder import load_audio
        waveform, sr = load_audio(
            sample("sine_300hz_8k_mono.wav"), target_sr=16000
        )
        assert sr == 16000
        assert abs(waveform.size - 8000) < 400

    def test_stereo_becomes_mono(self):
        """Stereo WAV must produce a 1-D (mono) waveform."""
        from backend.audio.decoder import load_audio
        waveform, _ = load_audio(
            sample("sine_440hz_22k_stereo.wav"), target_sr=16000
        )
        assert waveform.ndim == 1, (
            f"Stereo→mono conversion failed: shape is {waveform.shape}"
        )


class TestLoadAudioErrorPaths:
    """load_audio() must raise precise exceptions for bad inputs."""

    def test_missing_file_raises_file_not_found(self):
        from backend.audio.decoder import load_audio
        with pytest.raises(FileNotFoundError):
            load_audio("/tmp/definitely_does_not_exist_xyz.wav")

    def test_empty_file_raises_value_error(self):
        from backend.audio.decoder import load_audio
        with pytest.raises(ValueError, match="empty"):
            load_audio(sample("empty_file.wav"))

    def test_corrupt_file_raises_audio_decode_error(self):
        from backend.audio.decoder import AudioDecodeError, load_audio
        with pytest.raises(AudioDecodeError):
            load_audio(sample("corrupt_file.wav"))

    def test_unsupported_extension_raises(self):
        from backend.audio.decoder import UnsupportedFormatError, load_audio
        with tempfile.NamedTemporaryFile(suffix=".xyz", delete=False) as f:
            f.write(b"dummy")
            tmp_path = f.name
        try:
            with pytest.raises(UnsupportedFormatError):
                load_audio(tmp_path)
        finally:
            os.unlink(tmp_path)

    def test_directory_raises_is_a_directory_error(self):
        from backend.audio.decoder import load_audio
        with pytest.raises(IsADirectoryError):
            load_audio(str(SAMPLES_DIR))


# ===========================================================================
# 2. PREPROCESSING TESTS  (backend/audio/preprocessing.py)
# ===========================================================================

class TestPreprocessAudioOutputContract:
    """preprocess_audio() must always return a standardised waveform."""

    def test_output_is_ndarray(self):
        from backend.audio.preprocessing import preprocess_audio
        result = preprocess_audio(sample("sine_440hz_16k_mono.wav"))
        assert isinstance(result, np.ndarray)

    def test_output_dtype_float32(self):
        from backend.audio.preprocessing import preprocess_audio
        result = preprocess_audio(sample("sine_440hz_16k_mono.wav"))
        assert result.dtype == np.float32, f"Got {result.dtype}"

    def test_output_is_mono(self):
        from backend.audio.preprocessing import preprocess_audio
        result = preprocess_audio(sample("sine_440hz_16k_mono.wav"))
        assert result.ndim == 1, f"Expected 1-D, got shape {result.shape}"

    def test_output_is_16khz_samples(self):
        """0.5 s of 16 kHz input must yield ~8000 output samples."""
        from backend.audio.preprocessing import preprocess_audio
        result = preprocess_audio(sample("sine_220hz_16k_mono.wav"))
        # 0.5 s × 16000 Hz = 8000 samples
        assert abs(result.size - 8000) < 400

    def test_stereo_input_becomes_mono(self):
        from backend.audio.preprocessing import preprocess_audio
        result = preprocess_audio(sample("sine_440hz_22k_stereo.wav"))
        assert result.ndim == 1, (
            f"Stereo input must be converted to mono, got shape {result.shape}"
        )

    def test_44k_input_resampled_to_16k(self):
        """1 s @ 44.1 kHz must produce ~16000 samples at 16 kHz."""
        from backend.audio.preprocessing import preprocess_audio
        result = preprocess_audio(sample("sine_440hz_44k_mono.wav"))
        assert abs(result.size - 16000) < 800


class TestNormalization:
    """normalize_waveform() must produce peak-normalised output."""

    def test_loud_signal_peak_is_1(self):
        from backend.audio.preprocessing import normalize_waveform
        waveform = np.array([0.1, 0.5, -0.3, 0.8, -0.2], dtype=np.float32)
        normed = normalize_waveform(waveform)
        assert abs(float(np.abs(normed).max()) - 1.0) < 1e-6

    def test_already_normalised_unchanged_in_peak(self):
        from backend.audio.preprocessing import normalize_waveform
        waveform = np.array([-1.0, 0.5, -0.3, 0.9], dtype=np.float32)
        normed = normalize_waveform(waveform)
        assert abs(float(np.abs(normed).max()) - 1.0) < 1e-6

    def test_quiet_signal_peak_after_normalize(self):
        """A quiet (but non-silent) waveform must be amplified to peak=1."""
        from backend.audio.preprocessing import normalize_waveform
        waveform = np.full(100, 0.001, dtype=np.float32)
        waveform[50] = 0.002
        normed = normalize_waveform(waveform)
        assert abs(float(np.abs(normed).max()) - 1.0) < 1e-5

    def test_silent_waveform_returned_unchanged(self):
        """All-zeros waveform must NOT be amplified (avoid Inf/NaN)."""
        from backend.audio.preprocessing import normalize_waveform
        silent = np.zeros(1000, dtype=np.float32)
        result = normalize_waveform(silent)
        assert np.all(result == 0.0), "Silent waveform should remain all-zeros"

    def test_output_dtype_is_float32(self):
        from backend.audio.preprocessing import normalize_waveform
        waveform = np.array([0.1, -0.5, 0.3], dtype=np.float32)
        result = normalize_waveform(waveform)
        assert result.dtype == np.float32

    def test_output_has_no_nan_or_inf(self):
        from backend.audio.preprocessing import normalize_waveform
        waveform = np.random.randn(4000).astype(np.float32)
        result = normalize_waveform(waveform)
        assert np.isfinite(result).all(), "Output must not contain NaN or Inf"

    def test_preprocess_audio_produces_normalised_peak(self):
        """Full pipeline with normalize=True must produce peak ≤ 1.0."""
        from backend.audio.preprocessing import preprocess_audio
        result = preprocess_audio(
            sample("sine_440hz_16k_quiet.wav"), normalize=True
        )
        peak = float(np.abs(result).max())
        assert peak <= 1.0 + 1e-6, f"Peak {peak:.6f} exceeds 1.0"
        # Quiet input must be amplified close to 1.0
        assert peak > 0.98, f"Expected peak close to 1.0, got {peak:.4f}"

    def test_preprocess_audio_no_normalize_preserves_amplitude(self):
        """With normalize=False, amplitude should stay sub-normalised."""
        from backend.audio.preprocessing import preprocess_audio
        result = preprocess_audio(
            sample("sine_440hz_16k_quiet.wav"), normalize=False
        )
        peak = float(np.abs(result).max())
        # Amplitude 0.01 sine, PCM round-trip — peak should be well below 1
        assert peak < 0.05, f"Expected low peak without normalization, got {peak:.4f}"


class TestValidateWaveform:
    """validate_waveform() must raise PreprocessingError for bad inputs."""

    def _good(self) -> np.ndarray:
        return np.sin(np.linspace(0, 1, 16000)).astype(np.float32)

    def test_good_waveform_passes(self):
        from backend.audio.preprocessing import validate_waveform
        validate_waveform(self._good(), 16000)  # must not raise

    def test_wrong_dtype_raises(self):
        from backend.audio.preprocessing import PreprocessingError, validate_waveform
        with pytest.raises(PreprocessingError, match="float32"):
            validate_waveform(self._good().astype(np.float64), 16000)

    def test_2d_array_raises(self):
        from backend.audio.preprocessing import PreprocessingError, validate_waveform
        with pytest.raises(PreprocessingError, match="1-D"):
            validate_waveform(
                np.zeros((100, 2), dtype=np.float32), 16000
            )

    def test_empty_array_raises(self):
        from backend.audio.preprocessing import PreprocessingError, validate_waveform
        with pytest.raises(PreprocessingError, match="empty"):
            validate_waveform(np.array([], dtype=np.float32), 16000)

    def test_too_short_raises(self):
        from backend.audio.preprocessing import PreprocessingError, validate_waveform
        # 10 ms at 16 kHz = 160 samples — below 50 ms minimum
        tiny = np.zeros(160, dtype=np.float32)
        with pytest.raises(PreprocessingError, match="short"):
            validate_waveform(tiny, 16000)

    def test_nan_raises(self):
        from backend.audio.preprocessing import PreprocessingError, validate_waveform
        bad = self._good().copy()
        bad[100] = float("nan")
        with pytest.raises(PreprocessingError, match="non-finite"):
            validate_waveform(bad, 16000)

    def test_inf_raises(self):
        from backend.audio.preprocessing import PreprocessingError, validate_waveform
        bad = self._good().copy()
        bad[200] = float("inf")
        with pytest.raises(PreprocessingError, match="non-finite"):
            validate_waveform(bad, 16000)

    def test_wrong_sample_rate_raises(self):
        from backend.audio.preprocessing import PreprocessingError, validate_waveform
        with pytest.raises(PreprocessingError, match="16000"):
            validate_waveform(self._good(), 8000)

    def test_not_an_ndarray_raises(self):
        from backend.audio.preprocessing import PreprocessingError, validate_waveform
        with pytest.raises(PreprocessingError):
            validate_waveform([0.0, 1.0, -1.0], 16000)  # type: ignore[arg-type]


class TestGetAudioInfo:
    """get_audio_info() must return accurate AudioInfo metadata."""

    def test_returns_audio_info(self):
        from backend.audio.preprocessing import AudioInfo, get_audio_info
        info = get_audio_info(sample("sine_220hz_16k_mono.wav"))
        assert isinstance(info, AudioInfo)

    def test_sample_rate_is_16k(self):
        from backend.audio.preprocessing import get_audio_info
        info = get_audio_info(sample("sine_220hz_16k_mono.wav"))
        assert info.sample_rate == 16000

    def test_duration_approximately_correct(self):
        """0.5 s WAV → duration should be ≈ 0.5 s."""
        from backend.audio.preprocessing import get_audio_info
        info = get_audio_info(sample("sine_220hz_16k_mono.wav"))
        assert abs(info.duration_seconds - 0.5) < 0.05

    def test_not_silent_for_sine(self):
        from backend.audio.preprocessing import get_audio_info
        info = get_audio_info(sample("sine_440hz_16k_mono.wav"))
        assert not info.is_silent

    def test_path_is_absolute_string(self):
        from backend.audio.preprocessing import get_audio_info
        info = get_audio_info(sample("sine_440hz_16k_mono.wav"))
        assert os.path.isabs(info.path)

    def test_rms_positive_for_sine(self):
        from backend.audio.preprocessing import get_audio_info
        info = get_audio_info(sample("sine_440hz_16k_mono.wav"))
        assert info.rms_amplitude > 0


class TestPreprocessAudioErrorPaths:
    """preprocess_audio() must propagate errors from decoder cleanly."""

    def test_missing_file_raises(self):
        from backend.audio.preprocessing import preprocess_audio
        with pytest.raises(FileNotFoundError):
            preprocess_audio("/tmp/no_such_audio_xyz.wav")

    def test_corrupt_file_raises_audio_decode_error(self):
        from backend.audio.decoder import AudioDecodeError
        from backend.audio.preprocessing import preprocess_audio
        with pytest.raises(AudioDecodeError):
            preprocess_audio(sample("corrupt_file.wav"))

    def test_empty_file_raises_value_error(self):
        from backend.audio.preprocessing import preprocess_audio
        with pytest.raises(ValueError, match="empty"):
            preprocess_audio(sample("empty_file.wav"))

    def test_unsupported_format_raises(self):
        import tempfile, os
        from backend.audio.decoder import UnsupportedFormatError
        from backend.audio.preprocessing import preprocess_audio
        with tempfile.NamedTemporaryFile(suffix=".xyz", delete=False) as f:
            f.write(b"dummy content")
            tmp = f.name
        try:
            with pytest.raises(UnsupportedFormatError):
                preprocess_audio(tmp)
        finally:
            os.unlink(tmp)


class TestWaveformProperties:
    """End-to-end waveform property checks that assert mono + 16 kHz + float32."""

    @pytest.mark.parametrize("wav_file,approx_samples", [
        ("sine_440hz_44k_mono.wav",    16000),   # 1 s @ 44.1 k → 16000 samples
        ("sine_220hz_16k_mono.wav",    8000),    # 0.5 s @ 16 k → 8000 samples
        ("sine_300hz_8k_mono.wav",     8000),    # 0.5 s @ 8 k upsamp → 8000
        ("sine_440hz_22k_stereo.wav",  8000),    # 0.5 s stereo → mono, ~8000
    ])
    def test_output_is_mono_float32_16k(self, wav_file, approx_samples):
        from backend.audio.preprocessing import preprocess_audio
        result = preprocess_audio(sample(wav_file))

        # dtype
        assert result.dtype == np.float32, f"{wav_file}: dtype={result.dtype}"
        # dimensionality (mono)
        assert result.ndim == 1, f"{wav_file}: ndim={result.ndim}"
        # sample count within ±5 %
        tolerance = int(approx_samples * 0.05) + 200
        assert abs(result.size - approx_samples) <= tolerance, (
            f"{wav_file}: expected ~{approx_samples} samples, got {result.size}"
        )
        # No NaN / Inf
        assert np.isfinite(result).all(), f"{wav_file}: non-finite values found"
        # Peak ≤ 1.0 (normalisation applied)
        peak = float(np.abs(result).max())
        assert peak <= 1.0 + 1e-5, f"{wav_file}: peak {peak:.4f} > 1.0"


# ===========================================================================
# 3. INTEGRATION — full preprocess pipeline on a synthetic in-memory file
# ===========================================================================

class TestInMemorySynthetic:
    """Round-trip: generate WAV bytes → write temp file → preprocess → verify."""

    def _run(self, sr: int, channels: int = 1, freq: float = 440.0) -> np.ndarray:
        from backend.audio.preprocessing import preprocess_audio
        wav_bytes = _make_wav_bytes(
            sr=sr, freq=freq, duration=1.0, channels=channels
        )
        with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
            f.write(wav_bytes)
            tmp_path = f.name
        try:
            return preprocess_audio(tmp_path)
        finally:
            os.unlink(tmp_path)

    def test_8khz_mono_to_16k(self):
        result = self._run(sr=8000, channels=1)
        assert result.dtype == np.float32
        assert result.ndim == 1
        # 1 s upsampled: expect ~16000 samples
        assert abs(result.size - 16000) < 800

    def test_44khz_stereo_to_16k_mono(self):
        result = self._run(sr=44100, channels=2)
        assert result.ndim == 1, "Must be mono"
        assert result.dtype == np.float32
        # 1 s downsampled: expect ~16000 samples
        assert abs(result.size - 16000) < 800

    def test_already_16khz_mono_passthrough(self):
        result = self._run(sr=16000, channels=1)
        assert result.ndim == 1
        assert result.dtype == np.float32
        # 1 s @ 16 kHz = 16000 samples exactly
        assert abs(result.size - 16000) < 200

    def test_no_nan_in_any_output(self):
        for sr, ch in [(8000, 1), (16000, 1), (22050, 2), (44100, 1)]:
            result = self._run(sr=sr, channels=ch)
            assert np.isfinite(result).all(), f"NaN/Inf found for sr={sr} ch={ch}"


# ===========================================================================
# Direct execution entry point
# ===========================================================================

if __name__ == "__main__":
    import sys

    # Simple runner (no pytest needed for a quick check)
    test_classes = [
        TestFFmpegAvailability,
        TestLoadAudioReturnContract,
        TestLoadAudioSampleCounts,
        TestLoadAudioErrorPaths,
        TestPreprocessAudioOutputContract,
        TestNormalization,
        TestValidateWaveform,
        TestGetAudioInfo,
        TestPreprocessAudioErrorPaths,
        TestWaveformProperties,
        TestInMemorySynthetic,
    ]

    passed = failed = 0
    print("\n=== VoiceCloneDetection-SIH — Audio Pipeline Tests ===\n")

    for cls in test_classes:
        instance = cls()
        for name in [m for m in dir(cls) if m.startswith("test_")]:
            method = getattr(instance, name)
            label  = f"{cls.__name__}.{name}"
            try:
                # Handle parametrize manually for direct execution
                if name == "test_output_is_mono_float32_16k":
                    params = [
                        ("sine_440hz_44k_mono.wav",   16000),
                        ("sine_220hz_16k_mono.wav",   8000),
                        ("sine_300hz_8k_mono.wav",    8000),
                        ("sine_440hz_22k_stereo.wav", 8000),
                    ]
                    for p in params:
                        method(*p)
                else:
                    method()
                print(f"  PASS  {label}")
                passed += 1
            except Exception as exc:
                print(f"  FAIL  {label}\n        {type(exc).__name__}: {exc}")
                failed += 1

    print(f"\n{'='*55}")
    print(f"Result: {passed} passed, {failed} failed "
          f"({passed + failed} total).")
    sys.exit(0 if failed == 0 else 1)
